global:
  endpoint: "<remote_write_endpoint>"

kube-prometheus-stack:
  fullnameOverride: prometheus-coralogix
  # hack in order to bypass issue with kube-prometheus-stack chart which always prints empty labels if not adding this
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml#L47
  defaultRules:
    additionalRuleLabels:
      app: prometheus-coralogix
  prometheus:
    prometheusSpec:
      ## disable the extra label added to the monitors
      ## to allow monitors to be added outside of the chart
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      ## the global default scrape interval and timeout
      scrapeInterval: '1m'
      scrapeTimeout: '30s'
      secrets: ['coralogix-keys']
      remoteWrite:
        ## the coralogix account domain url
        - url: '{{ .Values.global.endpoint }}'
          name: 'crx'
          remoteTimeout: 120s
          ## the secret name and key name that hold the coralogix private key.
          bearerTokenFile: '/etc/prometheus/secrets/coralogix-keys/PRIVATE_KEY'
  grafana:
    enabled: false
  alertmanager:
    enabled: false