{
 "title": "Kubernetes Pod",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_time_s_total, k8s_namespace_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\"}, k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_utilization_1{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_By{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Major Page faults",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(container_memory_major_page_faults_1{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_By_total{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_errors_1_total{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  }
 ]
}