{
 "title": "Fluentd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Environment", "query": "prometheus" },
   {
    "name": "fluentd",
    "query": {
     "query": "label_values(fluentd_output_status_emit_count{}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(fluentd_output_status_emit_count{job=~\"$fluentd\"}, pod) "
    }
   },
   { "name": "thanosQueryFrontend", "label": "thanosQueryFrontend", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=\"$fluentd\"}"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=\"$fluentd\"}"
    }
   ]
  },
  {
   "title": "Non-Ready Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=\"$fluentd\"} - kube_daemonset_status_number_ready{daemonset=\"$fluentd\"}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)((kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"memory\"}))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cpu Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)((kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\"}))"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container, pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container!=\"\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 10 }, "options": { "content": "# Processing Rates " } },
  {
   "title": "Total Incoming Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Rec" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(fluentd_input_status_num_records_total{job=\"$fluentd\"}[5m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Current Emit Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Rec" } },
   "targets": [
    {
     "expr": "sum by (type, job)(rate(fluentd_output_status_emit_records{job=\"$fluentd\"}[5m]))",
     "legendFormat": "{{ job }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Current Size Of Queued And Stage Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job)(fluentd_output_status_buffer_total_bytes{job=\"$fluentd\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  { "title": "Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Current Retry Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (job, type)(fluentd_output_status_retry_count{job=\"$fluentd\"})",
     "legendFormat": "{{ job }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Total Flush Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (job, type)(fluentd_output_status_flush_time_count{job=\"$fluentd\"})",
     "legendFormat": "{{ job }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{job=\"$fluentd\"}[1m])) by (plugin_id)",
     "legendFormat": "{{ plugin_id }} - Output error "
    }
   ]
  }
 ]
}