variable "aws_region" {
  description = "AWS region to deploy to."
  type        = string
  default     = "eu-west-1"
}

variable "otel_config_path" {
  description = "Path to the rendered OpenTelemetry collector configuration file."
  type        = string
}

variable "otel_deb_url" {
  description = "URL of the OpenTelemetry collector .deb package."
  type        = string
  default     = "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.137.0/otelcol-contrib_0.137.0_linux_amd64.deb"
}

variable "instance_type" {
  description = "EC2 instance type to use."
  type        = string
  default     = "t3.small"
}

variable "ssh_key_name" {
  description = "Name of the AWS key pair to create/use."
  type        = string
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key used for the EC2 instance."
  type        = string
}

variable "ssh_private_key_path" {
  description = "Path to the SSH private key corresponding to ssh_public_key_path. Used for output convenience."
  type        = string
}

variable "ssh_ingress_cidrs" {
  description = "List of CIDR blocks allowed to SSH into the instance."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "tags" {
  description = "Additional tags to apply to created resources."
  type        = map(string)
  default     = {}
}

variable "enable_demo_workloads" {
  description = "Install and run demo systemd workloads (Prometheus exporters, OTLP app, and logger)."
  type        = bool
  default     = false
}

variable "enable_telemetrygen" {
  description = "Install and run telemetrygen on the collector host."
  type        = bool
  default     = false
}

variable "telemetrygen_version" {
  description = "Telemetrygen version to build when enable_telemetrygen is true."
  type        = string
  default     = "v0.137.0"
}

variable "telemetrygen_go_version" {
  description = "Go toolchain version used to build telemetrygen."
  type        = string
  default     = "1.24.0"
}

variable "telemetrygen_otlp_endpoint" {
  description = "OTLP gRPC endpoint telemetrygen should send to."
  type        = string
  default     = "127.0.0.1:4317"
}

variable "telemetrygen_insecure" {
  description = "Pass --otlp-insecure to telemetrygen."
  type        = bool
  default     = true
}

variable "telemetrygen_rate_per_second" {
  description = "Spans per second generated by telemetrygen."
  type        = number
  default     = 25
}

variable "telemetrygen_service_name" {
  description = "Service name reported by telemetrygen."
  type        = string
  default     = "eco-system-telemetrygen"
}

variable "telemetrygen_duration" {
  description = "Run duration passed to telemetrygen (e.g. 'inf' for continuous)."
  type        = string
  default     = "inf"
}

variable "coralogix_api_key" {
  description = "Coralogix private key used by the collector and telemetrygen (if enabled)."
  type        = string
  default     = ""
}
