apiVersion: v1
kind: Service
metadata:
  name:  {{ template "prometheus-agent.name" . }}
  namespace: {{ template "prometheus-agent.namespace" . }}
  labels:
    app: {{ template "prometheus-agent.name" . }}
    self-monitor: {{ .Values.prometheus.serviceMonitor.selfMonitor | quote }}
{{- if .Values.prometheus.service.labels }}
{{ toYaml .Values.prometheus.service.labels | indent 4 }}
{{- end }}
{{- if .Values.prometheus.service.annotations }}
  annotations:
{{ toYaml .Values.prometheus.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.prometheus.service.clusterIP }}
  clusterIP: {{ .Values.prometheus.service.clusterIP }}
{{- end }}
{{- if .Values.prometheus.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.prometheus.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.prometheus.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.prometheus.service.loadBalancerIP }}
{{- end }}
{{- if .Values.prometheus.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.prometheus.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if ne .Values.prometheus.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.prometheus.service.externalTrafficPolicy }}
{{- end }}
  ports:
  - name: {{ .Values.prometheus.prometheusSpec.portName }}
    {{- if eq .Values.prometheus.service.type "NodePort" }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
    {{- end }}
    port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.targetPort }}
{{- if .Values.prometheus.service.additionalPorts }}
{{ toYaml .Values.prometheus.service.additionalPorts | indent 2 }}
{{- end }}
  publishNotReadyAddresses: {{ .Values.prometheus.service.publishNotReadyAddresses }}
  selector:
    app.kubernetes.io/instance: {{ template "prometheus-agent.name" . }}
    app.kubernetes.io/name: prometheus
    prometheus: {{ template "prometheus-agent.name" . }}
{{- if .Values.prometheus.service.sessionAffinity }}
  sessionAffinity: {{ .Values.prometheus.service.sessionAffinity }}
{{- end }}
  type: "{{ .Values.prometheus.service.type }}"