{{- if .Values.prometheus.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-agent.name" . }}
  namespace: {{ template "prometheus-agent.namespace" . }}
  labels:
    app: {{ template "prometheus-agent.name" . }}
spec:
  {{- include "servicemonitor.scrapeLimits" .Values.prometheus.serviceMonitor | nindent 2 }}
  selector:
    matchLabels:
      app: {{ template "prometheus-agent.name" . }}
      release: {{ $.Release.Name | quote }}
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "prometheus-agent.namespace" .) | quote }}
  endpoints:
  - port: {{ .Values.prometheus.prometheusSpec.portName }}
    {{- if .Values.prometheus.serviceMonitor.interval }}
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.scheme }}
    scheme: {{ .Values.prometheus.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml .Values.prometheus.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.prometheus.serviceMonitor.bearerTokenFile }}
    {{- end }}
    path: "{{ trimSuffix "/" .Values.prometheus.prometheusSpec.routePrefix }}/metrics"
{{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.prometheus.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.prometheus.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}