name: Setup
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster:  # id of input
    description: 'Whether or not to create a kind cluster during setup'
    required: true
    default: "false"
  cluster-name: # id of input
    description: 'Name of the kind cluster to create'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3.5
      with:
        version: v3.12.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.0

    - name: Create kind cluster
      uses: helm/kind-action@v1.5.0
      if: ${{ inputs.create-kind-cluster == 'true' }}
      with:
        node_image: kindest/node:v1.24.12
        cluster_name: ${{ inputs.cluster-name }}

    - name: Add Dependencies
      shell: bash
      run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add coralogix-charts-virtual https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
