global:
  domain: "coralogix.com"
  clusterName: "ci-test"
  defaultApplicationName: "otel"
  defaultSubsystemName: "integration"
  logLevel: "warn"

  extensions:
    kubernetesDashboard:
      enabled: true
