version: 1
timeout: "1m"
cache:
  type: 'SQLite'

validators: 
  # Ignore all GitHub links since they are rate-limited.
  - regex: '(^http[s]?:\/\/)(www\.)?(github\.com\/).*'
    type: 'ignore'
  # Ignore links to pr Labels.
  - regex: '(^http[s]?:\/\/)(www\.)?(github\.com\/)coralogix\/telemetry-shippers(\/issues.*)'
    type: 'ignore'
  # Ignore links that includes 'assets' because the generated content will resolve them correctly.
  - regex: '.+/assets/.+'
    type: ignore
  # Ignore remote docs pages that reject or drop validator requests.
  - regex: '^https:\/\/dev\.mysql\.com\/doc\/refman\/8\.0\/en\/server-logs\.html$'
    type: ignore
  - regex: '^https:\/\/opentelemetry\.io\/docs\/collector\/configuration\/$'
    type: ignore
