{
 "title": "FluentBit",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Environment", "query": "prometheus" },
   {
    "name": "fluentbit",
    "query": {
     "query": "label_values(fluentbit_uptime, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(fluentbit_uptime{job=~\"$fluentbit\"}, pod)"
    }
   },
   { "name": "thanosQueryFrontend", "label": "thanosQueryFrontend", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"$fluentbit\"})"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{daemonset=~\"$fluentbit\"})"
    }
   ]
  },
  {
   "title": "Non-Ready Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"$fluentbit\"}) - sum(kube_daemonset_status_number_ready{daemonset=~\"$fluentbit\"})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)((kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cpu Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)((kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\"}))"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (container, pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container!=\"\"}[5m]))",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container!=\"\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 10 },
   "options": { "content": "# Processing Rates " },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (name, job)(rate(fluentbit_input_bytes_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (name, job)(rate(fluentbit_output_proc_bytes_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Rec" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (job, name)(rate(fluentbit_input_records_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Output Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Rec" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (job, name)(rate(fluentbit_output_proc_records_total{job=~\"$fluentbit\"}[5m]))",
     "legendFormat": "{{ job }} - {{ name }} "
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Records Dropped Per Filter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Rec" } },
     "targets": [
      {
       "expr": "sum by (name, job)(rate(fluentbit_filter_drop_records_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "{{ job }} - {{ name }} "
      }
     ]
    },
    {
     "title": "Total Records Added By Filter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Rec" } },
     "targets": [
      {
       "expr": "sum by(name, job)(rate(fluentbit_filter_add_records_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "{{ job }} - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Drops/Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Output Total Retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (job, name)(rate(fluentbit_output_retries_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "Total Retries - {{ job }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Output Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by (name, job)(rate(fluentbit_output_errors_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "{{ job }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Total Records Dropped Per Output",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Rec" } },
     "targets": [
      {
       "expr": "sum by (name, job)(rate(fluentbit_output_dropped_records_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "{{ job }} - {{ name }} "
      }
     ]
    },
    {
     "title": "Number Of Abandoned Batches",
     "type": "timeseries",
     "description": "Number of abandoned batches because the maximum number of re-tries was reached.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum by (job, name)(rate(fluentbit_output_retries_failed_total{job=~\"$fluentbit\"}[5m]))",
       "legendFormat": "{{ job }} - {{ name }} "
      }
     ]
    }
   ]
  }
 ]
}