global:
  domain: ""
  clusterName: ""
  defaultApplicationName: "otel"
  defaultSubsystemName: "integration"
  logLevel: "warn"
  collectionInterval: "30s"

  extensions:
    kubernetesDashboard:
      enabled: true

# set distribution to openshift for openshift clusters
distribution: ""
opentelemetry-agent:
  enabled: true
  presets:
    coralogixExporter:
      enabled: true
      privateKey: ${env:CORALOGIX_PRIVATE_KEY}
      pipelines: ["none"]
  config:
    exporters:
      otlp:
        # configure the public endpoint here
        endpoint: coralogix-opentelemetry-receiver:4317
        # this is not needed if you have valid tls certificate fronting receivers
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters:
            - otlp
        logs:
          exporters:
            - coralogix
        metrics:
          exporters:
            - coralogix

opentelemetry-cluster-collector:
  enabled: true
opentelemetry-agent-windows:
  enabled: false
opentelemetry-gateway:
  enabled: false
coralogix-ebpf-agent:
  enabled: false
