apiVersion: v2
name: otel-integration
description: OpenTelemetry Integration
version: 0.0.240
keywords:
  - OpenTelemetry Collector
  - OpenTelemetry Agent
  - OpenTelemetry Integration
  - Kubernetes
  - Coralogix
dependencies:
  - name: opentelemetry-collector
    alias: opentelemetry-agent
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-agent.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-agent-windows
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-agent-windows.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-cluster-collector
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-cluster-collector.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-receiver
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-receiver.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-gateway
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-gateway.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-agent-eks-fargate
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-agent-eks-fargate.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-agent-eks-fargate-monitoring
    version: "0.125.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-agent-eks-fargate-monitoring.enabled
  - name: coralogix-ebpf-profiler
    alias: coralogix-ebpf-profiler
    version: "0.0.14"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts
    condition: coralogix-ebpf-profiler.enabled
  - name: opentelemetry-ebpf-instrumentation
    alias: opentelemetry-ebpf-instrumentation
    version: "0.1.5"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts
    condition: opentelemetry-ebpf-instrumentation.enabled
  - name: coralogix-operator
    alias: coralogix-operator
    version: "1.0.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: coralogix-operator.enabled

sources:
  - https://github.com/coralogix/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
maintainers:
  - name: Coralogix
    email: platform@coralogix.com
