apiVersion: v2
name: otel-ingegration
description: OpenTelemetry Integration
version: 0.0.1
keywords:
  - OpenTelemetry Collector
  - OpenTelemetry Agent
  - OpenTelemetry Integration
  - Kubernetes
  - Coralogix
dependencies:
  - name: opentelemetry-collector
    alias: opentelemetry-collector-agent
    version: "0.64.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-collector-agent.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-collector-infrastucture
    version: "0.64.0"
    repository: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    condition: opentelemetry-collector-infrastucture.enabled
  - name: kube-state-metrics
    version: "5.8.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
sources:
  - https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
maintainers:
  - name: Coralogix
    email: platform@coralogix.com
