opentelemetry-agent:
  enabled: true

  config:
    extensions:
      health_check:
        endpoint: "[${env:MY_POD_IP}]:13133"

    receivers:
      kubeletstats:
        endpoint: "[${env:K8S_NODE_IP}]:10250"
      statsd:
        endpoint: "[${env:MY_POD_IP}]:8125"
      otlp:
        protocols:
          grpc:
            endpoint: "[${env:MY_POD_IP}]:4317"
          http:
            endpoint: "[${env:MY_POD_IP}]:4318"
      zipkin:
        endpoint: "[${env:MY_POD_IP}]:9411"
      jaeger:
        protocols:
          grpc:
            endpoint: "[${env:MY_POD_IP}]:14250"
          thrift_http:
            endpoint: "[${env:MY_POD_IP}]:14268"
          thrift_compact:
            endpoint: "[${env:MY_POD_IP}]:6831"
          thrift_binary:
            endpoint: "[${env:MY_POD_IP}]:6832"
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 30s
              static_configs:
                - targets:
                    - "[${env:MY_POD_IP}]:8888"

    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: "[${env:MY_POD_IP}]"
                    port: 8888

opentelemetry-cluster-collector:
  enabled: true
  config:
    extensions:
      health_check:
        endpoint: "[${env:MY_POD_IP}]:13133"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "[${env:MY_POD_IP}]:4317"
          http:
            endpoint: "[${env:MY_POD_IP}]:4318"
      jaeger:
        protocols:
          grpc:
            endpoint: "[${env:MY_POD_IP}]:14250"
          thrift_http:
            endpoint: "[${env:MY_POD_IP}]:14268"
          thrift_compact:
            endpoint: "[${env:MY_POD_IP}]:6831"
          thrift_binary:
            endpoint: "[${env:MY_POD_IP}]:6832"
      zipkin:
        endpoint: "[${env:MY_POD_IP}]:9411"

      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-infrastructure-collector
              scrape_interval: 30s
              static_configs:
                - targets:
                    - "[${env:MY_POD_IP}]:8888"
    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: "[${env:MY_POD_IP}]"
                    port: 8888

coralogix-ebpf-profiler:
  k8s_watcher:
    http:
      host: "[::]"
  profiling:
    profiling_otel_agent:
      otel:
        exporter:
        # configure the opentelemetry collector endpoint here
          endpoint: "[$(HOST_IP)]:4317"