opentelemetry-agent:
  enabled: true
  networkMode: ipv6

  config:
    extensions:
      health_check:
        endpoint: "[${env:MY_POD_IP}]:13133"
opentelemetry-cluster-collector:
  enabled: true
  networkMode: ipv6
  config:
    extensions:
      health_check:
        endpoint: "[${env:MY_POD_IP}]:13133"

coralogix-ebpf-profiler:
  k8s_watcher:
    http:
      host: "[::]"
  profiling:
    profiling_otel_agent:
      otel:
        exporter:
        # configure the opentelemetry collector endpoint here
          endpoint: "[$(HOST_IP)]:4317"
