variable "aws_region" {
  description = "AWS GovCloud region to deploy to (us-gov-west-1 or us-gov-east-1)."
  type        = string
  default     = "us-gov-west-1"
}

variable "aws_profile" {
  description = "AWS CLI profile to use for authentication."
  type        = string
  default     = ""
}

variable "vpc_id" {
  description = "ID of the VPC to deploy into. GovCloud accounts typically do not have a default VPC."
  type        = string
}

variable "subnet_id" {
  description = "ID of the subnet to deploy the EC2 instance into. Use a private subnet where possible."
  type        = string
}

variable "otel_config_path" {
  description = "Path to the rendered OpenTelemetry collector configuration file."
  type        = string
}

variable "otel_deb_url" {
  description = "URL or S3 path of the OpenTelemetry collector .deb package. In air-gapped environments, host this in an internal S3 bucket."
  type        = string
  default     = "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.137.0/otelcol-contrib_0.137.0_linux_amd64.deb"
}

variable "instance_type" {
  description = "EC2 instance type to use."
  type        = string
  default     = "t3.small"
}

variable "ssh_key_name" {
  description = "Name of the AWS key pair to create/use. Leave empty to skip key pair creation (e.g. when using SSM Session Manager)."
  type        = string
  default     = ""
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key. Required when ssh_key_name is set."
  type        = string
  default     = ""
}

variable "ssh_private_key_path" {
  description = "Path to the SSH private key corresponding to ssh_public_key_path. Used for output convenience."
  type        = string
  default     = ""
}

variable "ssh_ingress_cidrs" {
  description = "List of CIDR blocks allowed to SSH into the instance. Defaults to deny-all; restrict to your bastion or VPN CIDR."
  type        = list(string)
  default     = []
}

variable "otlp_ingress_cidrs" {
  description = "List of CIDR blocks allowed to send OTLP traffic (ports 4317/4318) to the collector. Restrict to application subnet CIDRs."
  type        = list(string)
  default     = []
}

variable "associate_public_ip_address" {
  description = "Whether to assign a public IP to the instance. Should be false in GovCloud private-subnet deployments."
  type        = bool
  default     = false
}

variable "tags" {
  description = "Additional tags to apply to created resources."
  type        = map(string)
  default     = {}
}

variable "enable_demo_workloads" {
  description = "Install and run demo systemd workloads (Prometheus exporters, OTLP app, and logger). Not recommended for production."
  type        = bool
  default     = false
}

variable "enable_telemetrygen" {
  description = "Install and run telemetrygen on the collector host. Requires outbound internet access to download Go. Not recommended for production."
  type        = bool
  default     = false
}

variable "telemetrygen_version" {
  description = "Telemetrygen version to build when enable_telemetrygen is true."
  type        = string
  default     = "v0.137.0"
}

variable "telemetrygen_go_version" {
  description = "Go toolchain version used to build telemetrygen."
  type        = string
  default     = "1.24.0"
}

variable "telemetrygen_otlp_endpoint" {
  description = "OTLP gRPC endpoint telemetrygen should send to."
  type        = string
  default     = "127.0.0.1:4317"
}

variable "telemetrygen_insecure" {
  description = "Pass --otlp-insecure to telemetrygen."
  type        = bool
  default     = true
}

variable "telemetrygen_rate_per_second" {
  description = "Spans per second generated by telemetrygen."
  type        = number
  default     = 25
}

variable "telemetrygen_service_name" {
  description = "Service name reported by telemetrygen."
  type        = string
  default     = "otel-govcloud-telemetrygen"
}

variable "telemetrygen_duration" {
  description = "Run duration passed to telemetrygen (e.g. 'inf' for continuous)."
  type        = string
  default     = "inf"
}

variable "coralogix_api_key" {
  description = "Coralogix Send-Your-Data API key injected as CORALOGIX_PRIVATE_KEY into the collector service."
  type        = string
  default     = ""
  sensitive   = true
}
