receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  filelog:
    start_at: end
    include:
      - /hostfs/var/lib/docker/containers/*/*.log
      
    include_file_path: true

    # add log.file.name to resource attributes
    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

  # add metrics
  awsecscontainermetricsd:

processors:
  resourcedetection:
    # ecs & docker detectors not required when using ecslogresourcedetection for logs
    detectors: [env, ec2, system]
    timeout: 2s
    override: false

  ecsattributes:
    container_id:
      sources:
        - "log.file.name"

  # only allow logs with container.name label
  filter/ecslogs:
    logs:
      include:
        match_type: regexp
        resource_attributes:
          - key: aws.ecs.container.name
            value: '.*'

  transform/logs:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["cx_container_id"], attributes["docker.id"])
          - set(attributes["aws_ecs_task_family"], attributes["aws.ecs.task.definition.family"])
          - set(attributes["image_id"], attributes["image.id"])
          - delete_key(attributes, "image.id")

  batch:
          
exporters:
  logging:
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "$APP_NAME"
    subsystem_name: "$SUB_SYS"
    application_name_attributes:
    - "aws.ecs.task.definition.family"
    subsystem_name_attributes:
    - "docker.name"
    - "log.file.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection
        - ecsattributes
        - filter/ecslogs
        - transform/logs
      exporters:
        - coralogix

    metrics:
      receivers:
        - awsecscontainermetricsd
      processors:
        - batch
      exporters:
        - coralogix
    
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - coralogix