receivers:
  filelog:
    start_at: beginning

    # note that the host filesystem is mounted at /hostfs
    include:
      - /hostfs/var/log/*.log
      - /hostfs/var/log/messages
      - /hostfs/var/log/dmesg
      - /hostfs/var/log/xm/*.log
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true

    # add log.file.name to resource attributes
    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

processors:
  resourcedetection:
    detectors: [env, ec2, system] # ecs & docker detectors not required when using ecslogresourcedetection for logs
    timeout: 2s
    override: false

  ecslogresourcedetection:
    
exporters:
  logging:
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "otel-collector"
    subsystem_name: "ecs"
    application_name_attributes:
    - "ecs.container.name"
    - "APP_NAME"
    subsystem_name_attributes:
    - "ecs.task.definition.family"
    - "log.file.name"
    - "SUB_SYS"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection
        - ecslogresourcedetection
      exporters:
        - coralogix
