receivers:
  filelog:
    start_at: beginning

    # note that the host filesystem is mounted at /hostfs
    include:
      - /hostfs/var/log/*.log
      - /hostfs/var/log/messages
      - /hostfs/var/log/dmesg
      - /hostfs/var/log/xm/*.log
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true

    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

processors:
  resourcedetection:
    detectors: [env, ec2, ecs, docker, system]
    timeout: 2s
    override: false
    
exporters:
  logging:
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    logs:
      endpoint: "$LOGS_ENDPOINT"
    private_key: "$PRIVATE_KEY"
    application_name: "OTel"
    subsystem_name: "ECS"
    application_name_attributes:
    - "APP_NAME"
    - "service.namespace"
    subsystem_name_attributes:
    - "SUB_SYS"
    - "aws.ecs.task.family"
    - "log.file.name"
    - "service.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection
      exporters:
        - coralogix
