receivers:
  filelog:
    start_at: beginning

    # note that the host filesystem is mounted at /hostfs
    include:
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true

    # add log.file.name to resource attributes
    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

processors:
  resourcedetection:
    detectors: [env, ec2, system] # ecs & docker detectors not required when using ecsattributes for logs
    timeout: 2s
    override: false

  ecsattributes:
    # add container ID sources
    container_id:
      sources:
        - "log.file.name"
        - "container.id"
    
exporters:
  logging:
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "$APP_NAME"
    subsystem_name: "$SUB_SYS"
    application_name_attributes:
      - "aws.ecs.container.name"
    subsystem_name_attributes:
      - "aws.ecs.task.definition.family"
      - "log.file.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection
        - ecsattributes
      exporters:
        - coralogix
