receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  prometheus:
    config:
      scrape_configs:
      - job_name: otel-collector-metrics
        scrape_interval: 60s
        static_configs:
        - targets: ['localhost:8888']

  filelog:
    start_at: end
    include:
      - /hostfs/var/lib/docker/containers/*/*.log

    include_file_path: true

    # add log.file.path to resource attributes
    operators:
      - type: move
        from: attributes["log.file.path"]
        to: resource["log.file.path"]

processors:
  resourcedetection:
    # ecs & docker detectors not required when using ecslogresourcedetection for logs
    detectors: [env, ec2, system]
    timeout: 2s
    override: false

  ecsattributes:
    container_id:
      sources:
        - "log.file.path"

  transform/logs:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["cx_container_id"], attributes["docker.id"])
          - set(attributes["aws_ecs_task_family"], attributes["aws.ecs.task.definition.family"])
          - set(attributes["image_id"], attributes["image.id"])
          - delete_key(attributes, "image.id")

  # otel-collector resource detection for collector
  resourcedetection/otel-collector:
    detectors: [ecs, ec2]
    timeout: 2s
    override: false

exporters:
  logging:
    verbosity: detailed
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "$APP_NAME"
    subsystem_name: "$SUB_SYS"
    application_name_attributes:
    - "aws.ecs.cluster"
    - "aws.ecs.cluster.name"
    - "aws.ecs.task.definition.family"
    subsystem_name_attributes:
    - "aws.ecs.container.name"
    - "aws.ecs.docker.name"
    - "docker.name"
    timeout: 30s

extensions:
  health_check:

service:
  extensions:
    - health_check

  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection
        - ecsattributes
        - transform/logs
      exporters:
        - coralogix

    traces:
      receivers:
        - otlp
      exporters:
        - coralogix

    metrics/otel-collector:
      receivers:
        - prometheus
      processors:
        - resourcedetection/otel-collector
      exporters:
        - coralogix

  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed
