{
 "title": "Host Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_cpu_time_total, host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - rate(system_cpu_time_total{state=\"idle\", host_name=\"$host\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( system_cpu_time_total{state=\"idle\", host_name=\"$host\"})\n)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m{host_name=\"$host\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "system_cpu_load_average_5m_1{host_name=\"$host\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "system_cpu_load_average_15m{host_name=\"$host\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(system_cpu_time_total{host_name=\"$host\",state=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_By{host_name=\"$host\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_By_total{host_name=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} {{direction}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_By{host_name=\"$host\"}",
     "legendFormat": "{{device}} {{state}}"
    }
   ]
  }
 ]
}