apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    app: telemetrygen
  name: telemetrygen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetrygen
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      restartPolicy: Always
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "$(NODE):4317"
        args:
          - "traces"
          - "--otlp-endpoint=172.18.0.2:4317"  # Use environment variable to dynamically set endpoint
          - "--otlp-insecure"
          - "--rate=1000"  # Set the desired RPS
          - "--duration=900s"