{
 "title": "Span Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(calls_total_total, k8s_namespace_name)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(calls_total_total, k8s_deployment_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(calls_total_total{k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\"}[$__rate_interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(calls_total_total{status_code=\"STATUS_CODE_ERROR\",k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\"}[$__rate_interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Call Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(latency_ms_bucket{k8s_namespace_name=\"$namespace\", k8s_deployment_name=\"$deployment\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}