apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}-{{ .DataType }}-deployment
  namespace: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Name }}-{{ .DataType }}-deployment
  template:
    metadata:
      annotations:
        workload: deployment
      labels:
        app: {{ .Name }}-{{ .DataType }}-deployment
    spec:
      restartPolicy: Always
      containers:
      - image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        env:
        - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP    
        args:
          - |
          {{ .DataType }} \
          --otlp-insecure \
          --otlp-endpoint=${NODE}:4317 \
          --duration=36000s \
          --rate=1 \
          --otlp-attributes=service.name="test-{{ .DataType }}-deployment" \
          {{- if eq .DataType "traces" }}
          --status-code= \
          {{- end }}
          ;
