apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}-{{ .DataType}}-job
  namespace: e2e
spec:
  template:
    metadata:
      annotations:
        workload: job
      labels:
        app: {{ .Name }}-{{ .DataType }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP    
        command:
        - /telemetrygen
        - {{ .DataType }}
        - --otlp-insecure
        - --otlp-endpoint={{ .OTLPEndpoint }}
        - --duration=36000s
        - --rate=1
        - --otlp-attributes=service.name="test-{{ .DataType }}-job"