apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-telemetrygen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ebpf-telemetrygen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ebpf-telemetrygen
      annotations:
        app.coralogix.com/service: ebpf-annotated-service
    spec:
      restartPolicy: Always
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:0.142.0
        imagePullPolicy: IfNotPresent
        env:
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        command:
        - /telemetrygen
        - traces
        - --otlp-insecure
        - --duration=36000s
        - --rate=1
        - --service=ebpf-telemetrygen
        - --otlp-endpoint=$(K8S_NODE_IP):4317
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
      - name: cpu-burn
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - "while true; do :; done"
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 200m
            memory: 64Mi
