scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: <SCRAPE-INTERVAL>
    static_configs:
      - targets: ['172.17.0.1:9100'] # target is the host
    relabel_configs:
      - target_label: instance
        replacement: '<HOSTNAME>'
      - target_label: cluster
        replacement: '<CLUSTERNAME>'
      - target_label: host_public_ip
        replacement: '<HOSTPUBLICIP>'
  - job_name: 'cAdvisor'
    scrape_interval: <SCRAPE-INTERVAL>
    static_configs:
      - targets: ['172.17.0.1:9101'] # target is the host
    relabel_configs:
      - target_label: instance
        replacement: '<HOSTNAME>'
remote_write:
- url: 'https://<ENDPOINT>/prometheus/api/v1/write'
  name: 'crx'
  remote_timeout: 120s
  bearer_token: '<PRIVATEKEY>'