name: Otel Integration Helm Lint And Install Test

on:
  pull_request:
    paths:
    - 'otel-integration/k8s-helm/**'

jobs:
  otel-integration-agent-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Setup cluster
        uses: ./.github/actions/setup
        with:
          create-kind-cluster: "true"
          cluster-name: "otel-integration-agent-e2e"
      - name: Save kubeconfig to file
        run: |
          kubectl config view --raw > /tmp/kind-otel-integration-agent-e2e
          echo "KUBECONFIG=/tmp/kind-otel-integration-agent-e2e" >> $GITHUB_ENV
          cat /tmp/kind-otel-integration-agent-e2e
      - name: Setup Secret
        run: kubectl create secret generic coralogix-keys --from-literal=PRIVATE_KEY=123
      - name: Install chart & telemetrygen for testing
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          cat /tmp/kind-otel-integration-agent-e2e
          cd ./otel-integration/k8s-helm
          helm dependency build
          helm upgrade --install otel-integration-agent-e2e . \
          --set global.clusterName="otel-integration-agent-e2e" \
          --set global.domain="coralogix.com"  \
          -f ./values.yaml \
          -f ./e2e-test/testdata/values-e2e-test.yaml
          kubectl wait --all --for=condition=ready --timeout=300s pod -l component=agent-collector
      - name: Run E2E test
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          cd ./otel-integration/k8s-helm/e2e-test/
          go test -v -run=TestE2E_Agent ./...

