
name: OpenTelemetry-Integration-Chart

on:
  push:
    branches: master
    paths:
    - 'otel-integration/k8s-helm/**'

env:
  CHART_VERSION: $(yq eval '.version' otel-integration/k8s-helm/Chart.yaml)
  CHART_NAME: otel-integration
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for the JFrog exchange
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://cgx.jfrog.io
        with:
          oidc-provider-name: github
          oidc-audience: jfrog-github
      -
        name: Setup Helm Repo
        env:
          ARTIFACTORY_USERNAME: ${{ steps.jfrog.outputs.oidc-user }}
          ARTIFACTORY_TOKEN: ${{ steps.jfrog.outputs.oidc-token }}
        run: |
          helm repo add coralogix-charts-virtual "${ARTIFACTORY_URL}coralogix-charts-virtual" --username "$ARTIFACTORY_USERNAME" --password "$ARTIFACTORY_TOKEN"
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update
          helm dependency build ./otel-integration/k8s-helm/
          cd otel-integration/k8s-helm
          helm package .
      -
        name: use-jfrog-cli
        run: |
          cd otel-integration/k8s-helm
          jf rt upload "${{ env.CHART_NAME }}-*.tgz" coralogix-charts
