permissions:
  contents: read
name: OpenTelemetry-ECS-EC2-Chart

on:
  push:
    branches: master
    paths:
    - 'otel-ecs-ec2/**'

env:
  CHART_VERSION: $(yq eval '.version' otel-ecs-ec2/Chart.yaml)
  CHART_NAME: ecs-ec2-integration
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for the JFrog exchange
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://cgx.jfrog.io
        with:
          oidc-provider-name: github
          oidc-audience: jfrog-github
      -
        name: Setup Helm Repo
        env:
          ARTIFACTORY_USERNAME: ${{ steps.jfrog.outputs.oidc-user }}
          ARTIFACTORY_TOKEN: ${{ steps.jfrog.outputs.oidc-token }}
        run: |
          helm repo add coralogix-charts-virtual "${ARTIFACTORY_URL}coralogix-charts-virtual" --username "$ARTIFACTORY_USERNAME" --password "$ARTIFACTORY_TOKEN"
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update
          helm dependency build ./otel-ecs-ec2/
          cd otel-ecs-ec2
          helm package .
      -
        name: use-jfrog-cli
        run: |
          cd otel-ecs-ec2
          jf rt upload "${{ env.CHART_NAME }}-*.tgz" coralogix-charts


