
name: OpenTelemetry-ECS

on:
  push:
    branches: master
    paths:
    - 'otel-agent/ECS/**'

env:
  DOCKERHUB_REGISTRY: coralogixrepo/otel-coralogix-ecs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Read otel VERSION file
        id: get-otel-version
        run: echo "::set-output name=version::$(cat ./otel-agent/ECS/VERSION)"
      -
        name: Build And Push otel Image To Dockerhub
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./otel-agent/ECS/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}:${{ steps.get-otel-version.outputs.version }}