name: Otel Integration Helm Lint And Install Test

on:
  pull_request:
    paths:
    - 'otel-integration/k8s-helm/**'

jobs:
  otel-integration-agent-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Setup cluster
        uses: ./.github/actions/setup
        with:
          create-kind-cluster: "true"
          cluster-name: "otel-integration-agent-e2e"
      - name: Save kubeconfig to file
        run: |
          kubectl config view --raw > /tmp/kind-otel-integration-agent-e2e
          echo "KUBECONFIG=/tmp/kind-otel-integration-agent-e2e" >> $GITHUB_ENV
      - name: Get and set Kind Host Endpoint
        shell: bash
        run: |
          docker network inspect kind
          if [[ "$(uname)" == "Darwin" ]]; then
              HOSTENDPOINT="host.docker.internal"
          else
              set +e  # Disable exit on error temporarily
              HOSTENDPOINT=$(docker network inspect kind | grep -A 5 '"Config": \[' | grep '"Gateway":' | grep -Eo '"Gateway": "[0-9.]+"' | grep -Eo '[0-9.]+')
              set -e  # Re-enable exit on error
              if [[ -z "$HOSTENDPOINT" ]]; then
                  echo "Failed to find host endpoint via docker network inspect"
              fi
          fi
          # Set the HOSTENDPOINT environment variable for GitHub Actions
          echo "HOSTENDPOINT=$HOSTENDPOINT" >> $GITHUB_ENV
          echo "HOSTENDPOINT is set to $HOSTENDPOINT"
      - name: Setup Secret
        run: kubectl create secret generic coralogix-keys --from-literal=PRIVATE_KEY=123
      - name: Install chart & telemetrygen for testing
        env:
          HOSTENDPOINT: ${{ env.HOSTENDPOINT }}
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          cd ./otel-integration/k8s-helm
          helm dependency build
          helm upgrade --install otel-integration-agent-e2e . \
          --set global.clusterName="otel-integration-agent-e2e" \
          --set global.domain="coralogix.com"  \
          -f ./values.yaml \
          -f ./e2e-test/testdata/values-e2e-test.yaml
          kubectl wait --all --for=condition=ready --timeout=300s pod -l component=agent-collector

      - name: Run E2E test
        env:
          HOSTENDPOINT: ${{ env.HOSTENDPOINT }}
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          cd ./otel-integration/k8s-helm/e2e-test/
          go test -v -run=TestE2E_Agent ./...

