{
 "title": "OpenTelemetry Collector",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appname",
    "query": {
     "query": "label_values(otelcol_exporter_sent_spans_total, __meta_applicationname)"
    }
   },
   {
    "name": "subsystem",
    "query": {
     "query": "label_values(otelcol_exporter_sent_spans_total, __meta_subsystem)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retry Queue Capacity vs Current Size (in Batches)",
     "type": "timeseries",
     "description": "This panel shows you if the queue capacity is enough for your workload. ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (exporter)(otelcol_exporter_queue_capacity)",
       "legendFormat": "{{ exporter }} - capacity"
      },
      {
       "expr": "sum by (exporter)(otelcol_exporter_queue_size)",
       "legendFormat": "{{ exporter }} - current size"
      }
     ]
    },
    {
     "title": "Failed Exported Spans",
     "type": "timeseries",
     "description": "The collector is not able to export data as expected. It's not necessarily means data loss because there can be retries, s but a high rate of failures can indicate issues with the network or backend receiving the data.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (exporter)(rate(otelcol_exporter_send_failed_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ exporter }} "
      }
     ]
    },
    {
     "title": "Sent Spans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (exporter)(rate(otelcol_exporter_sent_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ exporter }}"
      }
     ]
    },
    {
     "title": "Sent Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (exporter)(rate(otelcol_exporter_sent_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ exporter }}"
      }
     ]
    },
    {
     "title": "Number of Spans Failed to be Added to the Sending Queue",
     "type": "timeseries",
     "description": " This may be caused by a queue full of unsettled elements, so you may need to decrease your sending rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (exporter)(rate(otelcol_exporter_enqueue_failed_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ exporter }}"
      }
     ]
    },
    {
     "title": "Number of Metrics Failed to be Added to the Sending Queue",
     "type": "timeseries",
     "description": " This may be caused by a queue full of unsettled elements, so you may need to decrease your sending rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by (exporter)(rate(otelcol_exporter_enqueue_failed_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ exporter }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Spans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_accepted_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Received Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_accepted_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Refused Spans",
     "type": "timeseries",
     "description": "It indicates that too many errors are returned, it may indicate data loss",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_refused_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Refused Metrics",
     "type": "timeseries",
     "description": "It indicates that too many errors are returned, it may indicate data loss",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_refused_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Dropped Spans",
     "type": "timeseries",
     "description": "Dropped Spans for a sustained period of time means a data loss",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_dropped_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Dropped Metrics",
     "type": "timeseries",
     "description": "Dropped metrics for a sustained period of time means a data loss",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_dropped_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    },
    {
     "title": "Batch Processor Sent Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (processor)(rate(otelcol_processor_batch_batch_send_size_sum[10m]))",
       "legendFormat": "{{ processor }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Spans",
     "type": "timeseries",
     "description": "Received spans per receiver and transport type",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (receiver, transport)(rate(otelcol_receiver_accepted_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ receiver }}  - {{ transport }}"
      }
     ]
    },
    {
     "title": "Received Metrics",
     "type": "timeseries",
     "description": "Received metrics per receiver and transport type",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by (receiver, transport)(rate(otelcol_receiver_accepted_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ receiver }} - {{ transport }}"
      }
     ]
    },
    {
     "title": "Refused Spans",
     "type": "timeseries",
     "description": "It indicates that too many errors are returned, it may indicate data loss",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "group by (receiver, transport)(rate(otelcol_receiver_refused_spans_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ receiver }} - {{ transport }}"
      }
     ]
    },
    {
     "title": "Refused Metrics",
     "type": "timeseries",
     "description": "It indicates that too many errors are returned, it may indicate data loss",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "group by (receiver, transport)(rate(otelcol_receiver_refused_metric_points_total{__meta_applicationname=~\"$appname\", __meta_subsystem=~\"$subsystem\"}[10m]))",
       "legendFormat": "{{ receiver }} - {{ transport }}"
      }
     ]
    }
   ]
  }
 ]
}